### ISSUE TITLE
Users system

### ISSUE THREAD

**Issue by danimesq** [April93/Kaffiene#2] opened 2017-04-24 17:19 UTC

**Comment by April93** [comment] 2017-04-25 05:46
I've been considering this. The only issue is that it'd require a reworked database (not just the lame text file Kaffiene currently uses), and I'm concerned about quality control and duplicates. Look at ZeroWiki for a good example of this. Lots of duplicate data (bloating the site size), poor quality for many of the entries, etc. Along with that it opens up Kaffiene to possible abuse with people posting spam to it rather than genuinely adding sites.

The rest of the related issues have been marked as duplicates because they are. User accounts for Kaffiene isn't even a confirmed feature yet, let alone the various details. For now I'm going to close this, but I've been considering it and may reopen in the future.

**Closed as completed by April93** 2017-04-25 05:46 UTC
Labels: enhancement

**Comment by danimesq** [comment] 2017-04-25 10:20
I already suggested a reputation system (in #4) to avoid it, but the reply was:
"Outside the scope of Kaffiene."
I'm trying to understand you.

**Comment by April93** [comment] 2017-04-25 10:33
A reputation system is outside the scope of Kaffiene. I don't intend to play police or the moral authority. Kaffiene is a search engine, not a moral guidance tool. That's simply more bloat for the site that's entirely unneeded. User submissions are *already* a part of Kaffiene, but not in a direct sense (there's just a link to mail me about adding something). It makes sense to convert this to a field on the site. However, that leads to the problems mentioned. I'm still not sure about a good solution here.

Look at 0list for a good example on why I'm not exactly jumping at the idea. It's often filled with spam, bad entries, etc.  I think having a separate 'help me share my site' website would be better. Users go in, enter their new site address, and then have crawlers go there and add it to the various searches/indexes. This is *already* the case with [this site.](http://127.0.0.1:43110/1LtvsjbtQ2tY7SCtCZzC4KhErqEK3bXD4n/) The various site management tools for Kaffiene pull from there and match with zeroname. Letting users have direct control over Kaffiene's results I feel would be disastrous. Either way, it's a problem to think about long term. As of now it's not on the to-do list.

Any user features, thus, are entirely out of scope. The point is to add sites, not have an account system with various details that suck up dev work and don't help deliver results.
